### ISSUE TITLE
Doesn't Work with TIDAL HiFi

### ISSUE THREAD

**Issue by KorbsStudio** [NyaomiDEV/Sunamu#16]
Even with "MPRIS" enabled in the settings, Sunamu only shows the album cover.

https://user-images.githubusercontent.com/51213244/167315192-4bf4fee0-6567-4758-85f8-9a022710196f.mp4

**Comment by NyaomiDEV** [comment]
Hey Korbs! - Sorry but the project is on hold since I recently moved to macOS (an Apple Silicon MacBook to be precise) and I cannot really maintain Sunamu as is since I am still in search of a way to make it work on macOS (research and development is also on hold, since I got finals starting in June and I am still preparing a lot of stuff for those; of course academic stuff goes first, funny development goes second).

Didn't know Tidal Hi-Fi got a port to Linux, assuming that's community based it may as well be that their implementation is non-compliant or lacking, especially since Sunamu relies on proper event firing from the player's end while other MPRIS implementations sacrifice performance for reliability in worst-case scenarios via manual polling. I could also implement that, but I would prefer (and everyone wins) if this issue is taken to their issue tracker so that they can see if their implementation is strictly following the spec.

Doing an MPRIS2 implementation is straightforward, but doing it well enough is pain in the butt, especially in Electron.

**Comment by NyaomiDEV** [comment]
I am closing this issue since there are no updates on this client.

Sunamu will not adapt to specific clients, also because I took a brief look at their code and they miss the `Seeked` and `PropertiesChanged` events, which Sunamu uses to update its internal data.
