### ISSUE TITLE
CPU temp goes way up

### ISSUE THREAD

**Issue by horga83** [NyaomiDEV/Sunamu#25]
I'm trying to run this with GNOME 42, unfortunately while it works, I have noticed the CPU temperature climbs almost to 60C, normally it sits about 36C.

**Comment by NyaomiDEV** [comment]
What about the usage? CPU temperatures are not something I control, and the behaviour you are describing is odd; my CPU usage is nearly identical and temps are on check.

If you are running Sunamu on a weak system consider using higher polling rates and (if you are using Git) probably disabling karaoke mode will help.

If you are not displaying lyrics you can just poll each second since you don't need sub-second precision anyway.

**Comment by NyaomiDEV** [comment]
Look I took some measurements and Sunamu does not even eat 1% of my total CPU usage when it shows with lyrics and all.

Check your cooling system.
