### ISSUE TITLE
Background Playback

### ISSUE THREAD

**Issue by Arnab11** [NyaomiDEV/Sunamu#32]
Please make this app run in background/system tray.
and any way to change lyrics provider?

appreciate your work. this app is awesome.

**Comment by NyaomiDEV** [comment]
Assuming you are running on Windows (10 / 11). The app already runs in the background, as it's meant to be a desktop widget. It indeed will stay below other apps. If you want to close it, you can do so by right clicking on the cover art, and that will bring the classic Windows menu that you can use to close it.

If you're on Linux, you have to write a specific window rule for Sunamu, so that it behaves like intended. The enormous amount of window managers across X11 and Wayland makes it so it's impossible to get a known working formula that works over all distributions; not to mention that I am not a skilled developer by any means, so even if that were technically possible I lack the knowledge to make it.

As for the system tray, I am not really seeing why someone would love to have it. If the app behaves as a widget you don't need to minimize it, and if you want to close it you can close it by right clicking on the cover art (Windows) or by simply focusing it and hitting Alt + F4 (all configurations).

---

Sunamu supports, and checks for lyrics, in this order. Note that there's no way for an user to "add" a lyrics provider simply because there has to be code that handles it specifically.
- Musixmatch hosts a ton of lyrics, so it's always checked first.
- NetEase Music is especially useful for Asian people, so it's checked second.
- The third lyrics provider is Genius, which unfortunately provides static lyrics.

As a result, you cannot change the lyrics provider, as Sunamu already makes some best-effort guesswork to get you the lyrics to the song you're playing.
