### ISSUE TITLE
The metadata of the lyrics show up

### ISSUE THREAD

**Issue by CloudyWhale** [NyaomiDEV/Sunamu#39]
![metadata showing up in lyrics](https://user-images.githubusercontent.com/83542885/183524916-33954688-1d18-4523-b6db-e31b39c90379.png)
As you can see the metadata in the lyrics is showing up and it is driving me insane

**Comment by CloudyWhale** [comment]
This also happens to throw off the lyric timing

**Comment by CloudyWhale** [comment]
In spotify I don't have this issue 
![image](https://user-images.githubusercontent.com/83542885/183525104-0abbb65e-6536-4b78-b47b-8e70d02dbea0.png)

**Comment by NyaomiDEV** [comment]
This issue is largely inconsistent.

First off, Sunamu and Spotify use different lyrics sources (NetEase versus Musixmatch). To address your specific issue you MUST obtain a legit Musixmatch user token and configure Sunamu to use it. This will fix your timing issues as Musixmatch is generally on point with the track and it doesn't have any line of copyright embedded in the lyrics.

NetEase contributors specifically choose to embed copyright that way and I am not sure how someone could filter it out. Contributions are welcome.

**Comment by CloudyWhale** [comment]
How would I set up musixmatch?

**Comment by NyaomiDEV** [comment]
> How would I set up musixmatch?

You have to obtain a legit usertoken for Musixmatch (I cannot disclose how) and put it in the `mxmusertoken` field of Sunamu's configuration file.

**Comment by CloudyWhale** [comment]
I have figured out you can sign up for a musixmatch developers account but you cannot get synced lyrics with the free version :(

**Comment by CloudyWhale** [comment]
Is there any way to set genius as the primary lyric provider because I don't really care for synchronized lyrics

**Comment by CloudyWhale** [comment]
For some reason it is connecting to musixmatch succesfully

**Comment by CloudyWhale** [comment]
So how do I set musixmatch as the main lyrics provider?

**Comment by CloudyWhale** [comment]
> > How would I set up musixmatch?
> 
> You have to obtain a legit usertoken for Musixmatch (I cannot disclose how) and put it in the `mxmusertoken` field of Sunamu's configuration file.

That field is already filled in though. And it seems to work with songs that do not have there lyrics on netease. Is there a way to give musixmatch priority over netease music?

**Comment by NyaomiDEV** [comment]
It already has priority over NetEase. If Musixmatch lyrics are now working, try deleting all the Lyrics Cache and refilling it again. It should query Musixmatch correctly in 2.1.0.

**Comment by CloudyWhale** [comment]
Where is that stored?
