### ISSUE TITLE
Language Mismatch when no lyrics are found.

### ISSUE THREAD

**Issue by AG4lyf** [NyaomiDEV/Sunamu#53]
system language is "en" but when no lyrics are found it writes in wrong language. other then the one specified 
example 
![image](https://user-images.githubusercontent.com/45149585/190209497-d9fbedd2-3308-4d8c-9e5b-3b9b79d00193.png)

**Comment by AG4lyf** [comment]
ps. this is different from "No lyrics available" 
test subject - https://www.youtube.com/watch?v=D2STcRnJnGw

**Comment by NyaomiDEV** [comment]
The issue here is with NetEase Lyrics serving you lyrics for a song that probably is not what you expect, and on top of that the song it's expecting to be is also an instrumental one.

This has no effect on Sunamu, as the strings are reported by NetEase which is a Chinese service.

Therefore, this issue is invalid.

**Comment by AG4lyf** [comment]
Then allowing to not use specific lyrics provider would be nice ?

**Comment by NyaomiDEV** [comment]
Make a PR for it.
