### ISSUE TITLE
Some sort of graphical bug

### ISSUE THREAD

**Issue by NagisaLoop** [NyaomiDEV/Sunamu#60]
i recently switched from GNOME to KDE Plasma and i've been getting this weird [graphical issue](https://imgur.com/a/CJX1qML) where the ui keeps overlapping itself. it could just be kde, because it worked fine on gnome i use Pop!_OS 22.04 :) 

there's no errors when running it through the terminal, i feel like i didn't give enough information, so if you need more i'll happily give it

**Comment by NyaomiDEV** [comment]
let's start with the quick one: if you're planning on using this NOT as a widget then set `widgetMode` to false in the configuration and that won't happen.

if you wanted to use it as a widget, then I can't really do a thing about it because that bug has been in electron since forever and it varies from driver package to driver package, and from DE to DE, and from X11 to Wayland; it's really a YMMV thing. You could find that closing and reopening Sunamu a handful of times fixes that magically, but that *is* the problem to begin with.

In the end, if you got a beefy CPU you could disable hardware acceleration altogether but then Sunamu will lag like hell, so I am NOT recommending that.

**Comment by NagisaLoop** [comment]
turning widget mode off totally worked, thx so much :smile:
