### ISSUE TITLE
does not recognize google-chrome on cinnamon 

### ISSUE THREAD

**Issue by hans-mainz** [NyaomiDEV/Sunamu#66]
It works fine on KDE-Plasma, but it does not recognize when music is played with google chrome on cinnamon desktop enviroment.

**Comment by NyaomiDEV** [comment]
This is very much intended behaviour.

KDE Plasma has a Chrome extension to tightly integrate that with the system, and it also brings in media playback through MPRIS. If Cinnamon doesn't provide such a "glue" to the system, then Sunamu cannot show anything because it queries the MPRIS bus for media controls and metadata.
